import type { Metadata } from "next";
import { Tilt_Neon } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.scss";
import { ProviderAudio } from "@/contexts/providerAudio";
import { ProviderLayout } from "@/contexts/providerLayout";
import { ProviderStore } from "@/hooks/redux/provider";
import ProviderAuth from "@/contexts/providerAuth";

const inter = Tilt_Neon({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yuta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderStore>
          <ProviderAuth>
            <ProviderLayout>
              <ProviderAudio>{children}</ProviderAudio>
            </ProviderLayout>
          </ProviderAuth>
        </ProviderStore>
        <ToastContainer />
      </body>
    </html>
  );
}
